package com.controller;


import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.ExposesResourceFor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.domain.Leaderboard;
import com.repository.LeaderboardRepository;

@CrossOrigin(origins = "*")
@RestController
@ExposesResourceFor(Leaderboard.class)
@RequestMapping(value = "/leaderboard", produces = "application/json")
//@Controller    // This means that this class is a Controller
//@RequestMapping(path="/questions") // This means URL's start with /addLeaderboard (after Application path)
public class LeaderboardController {
	@Autowired // This means to get the bean called LeaderboardRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private LeaderboardRepository leaderboardRepository;
	
	@RequestMapping(method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody ResponseEntity<Leaderboard> addQuestion (@RequestBody Leaderboard leaderboard
			) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Leaderboard createdLeaderboard = leaderboardRepository.save(leaderboard);
		return new ResponseEntity(createdLeaderboard,HttpStatus.CREATED);
	}

	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody ResponseEntity<Iterable<Leaderboard>> getLeaderboards() {
		// This returns a JSON or XML with the questions
		return new ResponseEntity<>(leaderboardRepository.findAll(), HttpStatus.OK);
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public ResponseEntity<Leaderboard> findLeaderboardById(@PathVariable Integer id) {
		Optional<Leaderboard> leaderboard = leaderboardRepository.findById(id);

		if (leaderboard.isPresent()) {
			return new ResponseEntity<>(leaderboard.get(), HttpStatus.OK);
		}
		else {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.PUT, consumes = "application/json")
	public ResponseEntity<Leaderboard> updateLeaderboard(@PathVariable Integer id, @RequestBody Leaderboard leaderboard) {
		Leaderboard updatedLeaderboardText  = leaderboardRepository.save(leaderboard);
		System.out.println("ID:"+id+":");
		if (leaderboardRepository.existsById(id)) {
			return findLeaderboardById(id);
		}
		else {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}
}