package com.controller;


import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.ExposesResourceFor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.domain.PersonalDetails;
import com.repository.PersonalDetailsRepository;

@CrossOrigin(origins = "*")
@RestController
@ExposesResourceFor(PersonalDetails.class)
@RequestMapping(value = "/personalDetails", produces = "application/json")
//@Controller    // This means that this class is a Controller
//@RequestMapping(path="/questions") // This means URL's start with /addQuestions (after Application path)
public class PersonalDetailsController {
	@Autowired // This means to get the bean called QuestionsRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PersonalDetailsRepository personalDetailsRepository;
	
	@RequestMapping(method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody ResponseEntity<PersonalDetails> addDetails (@RequestBody PersonalDetails personalDetails
			) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		PersonalDetails createdpersonDetails = personalDetailsRepository.save(personalDetails);
		return new ResponseEntity(createdpersonDetails,HttpStatus.CREATED);
	}

	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody ResponseEntity<Iterable<PersonalDetails>> getAllDetails() {
		// This returns a JSON or XML with the questions
		return new ResponseEntity<>(personalDetailsRepository.findAll(), HttpStatus.OK);
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public ResponseEntity<PersonalDetails> findDetailById(@PathVariable Integer id) {
		Optional<PersonalDetails> details = personalDetailsRepository.findById(id);

		if (details.isPresent()) {
			return new ResponseEntity<>(details.get(), HttpStatus.OK);
		}
		else {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.PUT, consumes = "application/json")
	public ResponseEntity<PersonalDetails> updateQuestion(@PathVariable Integer id, @RequestBody PersonalDetails details) {
		PersonalDetails updatedDetails  = personalDetailsRepository.save(details);
		System.out.println("ID:"+id+":");
		if (personalDetailsRepository.existsById(id)) {
			return findDetailById(id);
		}
		else {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}
}