package com.controller;


import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.hateoas.ExposesResourceFor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.domain.Question;
import com.repository.QuestionsRepository;

@CrossOrigin(origins = "*")
@RestController
@ExposesResourceFor(Question.class)
@RequestMapping(value = "/questions", produces = "application/json")
//@Controller    // This means that this class is a Controller
//@RequestMapping(path="/questions") // This means URL's start with /addQuestions (after Application path)
public class QuestionController {
	@Autowired // This means to get the bean called QuestionsRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private QuestionsRepository questionRepository;
	
	@RequestMapping(method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
	public @ResponseBody ResponseEntity<Question> addQuestion (@RequestBody Question question
			) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Question createdQuestion = questionRepository.save(question);
		return new ResponseEntity(createdQuestion,HttpStatus.CREATED);
	}

	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody ResponseEntity<Iterable<Question>> getAllQuestions() {
		// This returns a JSON or XML with the questions
		return new ResponseEntity<>(questionRepository.findAll(), HttpStatus.OK);
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	public ResponseEntity<Question> findQuestionById(@PathVariable Integer id) {
		Optional<Question> question = questionRepository.findById(id);

		if (question.isPresent()) {
			return new ResponseEntity<>(question.get(), HttpStatus.OK);
		}
		else {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}
	
	@RequestMapping(value = "/{id}", method = RequestMethod.PUT, consumes = "application/json")
	public ResponseEntity<Question> updateQuestion(@PathVariable Integer id, @RequestBody Question question) {
		Question updatedQuestionText  = questionRepository.save(question);
		System.out.println("ID:"+id+":");
		if (questionRepository.existsById(id)) {
			return findQuestionById(id);
		}
		else {
			return new ResponseEntity<>(HttpStatus.NOT_FOUND);
		}
	}
}